name: Deploy to heroku

on:
    push:
        branches:
            - depelop # Edit your Main Branch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.8
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  procfile: "web: npm run start:heroku"
              env:
                  # Don't forget to prefix variables in your scripts with `HD_`!
                  # * Not required at the beginning of the environment variable to be registered on the Github side.
                  # HD_MONGODB_URI: ${{secrets.MONGODB_URI}}
